### ISSUE TITLE
README should explain what Mercator actually *does*

### ISSUE THREAD

**Issue by ncoghlan** [fabric8-analytics/mercator-go#12]
The current README doesn't actually explain what problem Mercator solves, why you might be interested in using it independently of the rest of fabric8-analytics, and how to run it if you are.

I noticed this as I was trying to remember whether or not Mercator 2.0 still handled the "Here's a directory, tell me about all the non-RPM components you find" use case, and looking at the README didn't help me at all in answering that question :)

/cc @shaded-enmity

**Comment by shaded-enmity** [comment]
Oh right, the README needs some care, I'll open a PR with an update by the end of the week :)

Thanks!

**Comment by ncoghlan** [comment]
Thanks!
