### ISSUE TITLE
Fails to build on Mac

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/mercator-go#38]
```
main.go:36:2: build constraints exclude all Go files in
/Users/xyz/f8a/mercator-go/src/github.com/fabric8-analytics/mercator-go/core/fileutils
```

```
# ls core/fileutils/
fileutils_linux.go  fileutils_windows.go
```

so we probably need also a `fileutils_mac.go` ?

CC @rootAvish

**Comment by jpopelka** [comment]
@shaded-enmity do you think we need also a `core/fileutils/fileutils_mac.go` or how does it work actually ?

**Comment by jpopelka** [comment]
Found it here: http://blog.ralch.com/tutorial/golang-conditional-compilation/

So we really need to add a `"fileutils_$(go env GOOS).go"` into `core/fileutils/`.

@rootAvish what does `go env GOOS` show on your Mac machine ?

You can also try to copy `fileutils_linux.go` to `"fileutils_$(go env GOOS).go"`, check if the build succeedes and if not, do necessary changes to make it build (yeah, you'll probably need to learn a bit of golang).

**Comment by shaded-enmity** [comment]
@jpopelka yeah, `fileutils_darwin.go` is the way to go - I think the implementation can be copy&pasted from the linux one, as the semantics of hiddne files on Mac work the same way as in Linux, but someone with a Mac should confirm.

**Comment by rootAvish** [comment]
@shaded-enmity Yeah, the build passed for me with that. Opened a PR for it.
